[package]
name = "minitar"
version = "0.1.0"
authors = ["geno nullfree <nullfree.geno@gmail.com> <nullfree.geno@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
